# Generated by Django 2.2.2 on 2019-06-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(blank=True, null=True)),
                ('pokelevel', models.IntegerField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('maxhp', models.IntegerField(blank=True, null=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('spatk', models.IntegerField(blank=True, null=True)),
                ('spdef', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Pokemon',
            },
        ),
        migrations.CreateModel(
            name='PokemonKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('type1', models.IntegerField(blank=True, null=True)),
                ('type2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PokemonKind',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('pokedex', models.ManyToManyField(through='pokemon.Pokemon', to='pokemon.PokemonKind')),
            ],
            options={
                'db_table': 'Trainer',
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.PokemonKind'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='pokemon.Trainer'),
        ),
    ]
